version: '3.7'

services:
    node-graphql:
        container_name: node-graphql
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
            target: development
        environment:
            - SERVER_PORT=${SERVER_PORT}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./:/usr/src/app:cached
        command: yarn dev
        env_file:
            - .env
        networks:
            - webnet

networks:
    webnet:
